"""Temporary compatibility shim for legacy ``NCSSQL57`` imports.

During migration, import backend symbols from ``scheduler`` directly.
"""

from warnings import warn as _warn

from scheduler import (
    ASSIGNMENT_DEBUG_LOGGER,
    AssignmentDebugLogger,
    AssignmentHistory,
    DatabaseMixin,
    MetricsCollector,
    NurseManager,
    NurseScheduler,
    NurseSchedulerUI,
    PerformanceProfiler,
    PerformanceReport,
    PhaseMetrics,
    PreScheduler,
    ScheduleQuality,
    SchedulerConfig,
    ScheduleState,
    ScheduleVariant,
    SharedSettings,
    ViolationHistoryService,
    VisualCalendarUI,
    WeekendHistory,
    WeekendHistoryService,
    WeekendPattern,
    WorkerMetrics,
    _accept,
    _dbg_pairs,
    _dbg_variants,
    _evaluate_variant_worker,
    _evaluate_variant_worker_profiled,
    _open_dbg,
    _pair,
    _reject,
    build_scheduler_config_from_settings,
    build_scheduler_from_settings,
    configure_assignment_debug_logger,
    configure_pair_variant_debug,
)

_warn(
    "NCSSQL57 is deprecated and will be removed in a future release. "
    "Import from scheduler instead.",
    DeprecationWarning,
    stacklevel=2,
)

__all__ = [
    "AssignmentDebugLogger",
    "ASSIGNMENT_DEBUG_LOGGER",
    "AssignmentHistory",
    "DatabaseMixin",
    "MetricsCollector",
    "NurseManager",
    "NurseScheduler",
    "NurseSchedulerUI",
    "PerformanceProfiler",
    "PerformanceReport",
    "PhaseMetrics",
    "PreScheduler",
    "ScheduleQuality",
    "SchedulerConfig",
    "ScheduleState",
    "ScheduleVariant",
    "SharedSettings",
    "VisualCalendarUI",
    "ViolationHistoryService",
    "WeekendHistory",
    "WeekendHistoryService",
    "WeekendPattern",
    "WorkerMetrics",
    "_accept",
    "_dbg_pairs",
    "_dbg_variants",
    "_evaluate_variant_worker",
    "_evaluate_variant_worker_profiled",
    "_open_dbg",
    "_pair",
    "_reject",
    "build_scheduler_config_from_settings",
    "build_scheduler_from_settings",
    "configure_assignment_debug_logger",
    "configure_pair_variant_debug",
]
